
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract Queue {
    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        // The current smart contract agrees to buy some gas to finish the
        // current transaction. This actions required to process external
        // messages, which bring no value (henceno gas) with themselves.
        tvm.accept();
    }

    modifier checkOwnerAndAccept() {
        require(tvm.pubkey() == msg.pubkey(), 102);
        tvm.accept();
        _;
    }

    mapping(uint => string) public person;
    uint next = 0;
    uint prev = 0;

    function addToQueue(string value) public checkOwnerAndAccept{
        person[next] = value;
        next++;
    }

    function leftFromQueue() public checkOwnerAndAccept{
        require(!person.empty(), 102);
        delete person[prev];
        prev++;
    }
}
